##################################
# Localhost URL's
#################################


### Get all contactss
GET http://127.0.0.1:3000/contacts

### Get contacts by id
GET http://127.0.0.1:3000/contacts/67895de8581a6bb051697336

### Create a new contacts
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Cibely",
    "lastName": "Melo",
    "email": "ci@example.com",
    "favoriteColor": "blue",
    "birthday": "2000-01-01"
}

### view new contacts
GET http://127.0.0.1:3000/contacts/67895de8581a6bb051697336

### update contacts
PUT http://127.0.0.1:3000/contacts/67915d738d3af954c90b4636
Content-Type: application/json

{
    "firstName": "Cibely",
    "lastName": "Melo",
    "email": "cibely.melo@example.com",
    "favoriteColor": "blue",
    "birthday": "1994-04-04"
}   

### delete contacts
DELETE http://127.0.0.1:3000/contacts/6793f984ec6f01cea579dfbe

##################################
# Render URL's
#################################

### Get all contacts
GET https://cse341-4zv7.onrender.com/contacts

### Get contacts by id
GET https://cse341-4zv7.onrender.com/contacts/67895de8581a6bb051697336

### Create a new contacts
POST https://cse341-4zv7.onrender.com/contacts
Content-Type: application/json

{
    "firstName": "Maria",
    "lastName": "Melo",
    "email": "cibely@example.com",
    "favoriteColor": "blue",
    "birthDate": "2000-01-01"
}

### view new contacts
GET https://cse341-4zv7.onrender.com/contacts/67895de8581a6bb051697336

### update contacts
PUT https://cse341-4zv7.onrender.com/contacts/67914ec21bbccc854348ba7f
Content-Type: application/json

{
    "firstName": "Cibely",
    "lastName": "Melo",
    "email": "cibely.melo@example.com",
    "favoriteColor": "blue",
    "birthDate": "1994-04-04"
}   

### delete contacts
DELETE https://cse341-4zv7.onrender.com/contacts/67914ec21bbccc854348ba7f

