##################################
# Localhost URL's
#################################


### Get all contacts
GET http://127.0.0.1:3000/contact

### Get contact by id
GET http://127.0.0.1:3000/contact/67895de8581a6bb051697336

### Create a new contact
POST http://localhost:3000/contact
Content-Type: application/json

{
    "firstName": "Cibely",
    "lastName": "Melo",
    "email": "ci@example.com",
    "favoriteColor": "blue",
    "birthday": "2000-01-01"
}

### view new contact
GET http://127.0.0.1:3000/contact/67895de8581a6bb051697336

### update contact
PUT http://127.0.0.1:3000/contact/67915d738d3af954c90b4636
Content-Type: application/json

{
    "firstName": "Cibely",
    "lastName": "Melo",
    "email": "cibely.melo@example.com",
    "favoriteColor": "blue",
    "birthday": "1994-04-04"
}   

### delete contact
DELETE http://127.0.0.1:3000/contact/6793f984ec6f01cea579dfbe

##################################
# Render URL's
#################################

### Get all contacts
GET https://cse341-4zv7.onrender.com/contact

### Get contact by id
GET https://cse341-4zv7.onrender.com/contact/67895de8581a6bb051697336

### Create a new contact
POST https://cse341-4zv7.onrender.com/contact
Content-Type: application/json

{
    "firstName": "Maria",
    "lastName": "Melo",
    "email": "cibely@example.com",
    "favoriteColor": "blue",
    "birthDate": "2000-01-01"
}

### view new contact
GET https://cse341-4zv7.onrender.com/contact/67895de8581a6bb051697336

### update contact
PUT https://cse341-4zv7.onrender.com/contact/67914ec21bbccc854348ba7f
Content-Type: application/json

{
    "firstName": "Cibely",
    "lastName": "Melo",
    "email": "cibely.melo@example.com",
    "favoriteColor": "blue",
    "birthDate": "1994-04-04"
}   

### delete contact
DELETE https://cse341-4zv7.onrender.com/contact/67914ec21bbccc854348ba7f

